### ISSUE TITLE
Roadmap to 0.4.0

### ISSUE THREAD

**Issue by seankross** [seankross/ari#49]
- [x] get rid of text2speech specific code
- [ ] specify/document voice engine API (https://github.com/jhudsl/ari/pull/57)
- [x] generally reduce number of arguments in functions (especially relating to ffmpeg)
- [ ] write a vignette about what kinds of args to pass to ffmpeg
- [x] See if the burning subtitles functions work.
- [ ] Should write some new tests for Ari that use tts coqui since it's free. A really cool test would go from tts to stt. (likely these only get run locally and not on cran)

Bonus:
- [x] spin out ariExtra functions into separate utility packages

**Comment by seankross** [comment]
``` r
 function(images, paragraphs,
                     output = tempfile(fileext = ".mp4"),
                     voice_engine = seantalk::talk,
                     subtitles = FALSE,
                     duration = NULL,
                     engine_args = list(helium = TRUE, service = "seanbox"),
                     key_or_json_file = NULL,
                     ...)


                     
wav <- do.call(voice_engine, args = engine_args)
# check that it's a list with a named object called wav that contains a tuneR::Wave
wav <- reduce(wav$wav, bind)
wav <- pad_wav(wav, duration = duration[i])
```

**Comment by howardbaik** [comment]
@cansavvy This is a roadmap of the next release of ari that came out of my meeting with Sean.

**Comment by howardbaik** [comment]
I documented the relationship between the main ari functions [here](https://docs.google.com/presentation/d/1Vjvq7PYuWsTkGi2EkXpnk0KtQYhbPSidBhMFQcqyb8I/edit#slide=id.g24d14489617_0_0)

**Comment by cansavvy** [comment]
I'm super excited about this. But I think since I wasn't in the meeting these bullet points lead me to more questions than me understanding the roadmap. Would love to meet with everyone involved to chat and divide up tasks/roles for this project.
